### ISSUE TITLE
최신업스트림 한글입력 버그

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonikr-albert#5]
#### Environment

최신 버전으로 설치 후 한글 입력이 불가능한 버그
QT버전이 6으로 올라가면서 한글입력이 아직 제대로 해결되지 않음

**Comment by gbdngb12** [comment]
안녕하세요.
한가지 궁금한점이 있습니다.
현재 albert에서 한글을 사용하면 현재 입력중인 끝글자는 query로 취급되지 않습니다.
예를 들어
```
gg 한글검색
```
과 같은 쿼리를 입력한다고 할때, `색`은 현재 입력중이므로 query에 반영되지 않고 여기서 Enter로 Query Action을 수행하면 `한글검`으로 구글 검색이 이루어집니다. 이러한 문제를 해결하려면 입력기를 고쳐야하는지, albert를 고쳐야하는지, qt framework에서 손을 봐야하는지 궁금합니다.

참고로 저는 https://github.com/albertlauncher/albert/issues/1130
albert를 임시 패치하여 문제를 해결하여 사용중입니다.

**Comment by chaeya** [comment]
입력기에서 바르게 전달한다고 해도 GTK나 QT 같은 개발환경에서 결국 IME 처리가 필요하기 때문에 albert 를 수정하는것이 맞을것 같습니다만 해외 프로젝트들의 경우 끝글자 버그에 대해서 인식하지 못하거나 이해가 어려운 경우가 많아서 반영이 잘 안되는것 같습니다. 
수정하신 패치가 잘 동작한다면 패치를 적용한 버전으로 한국어 사용자들에게 배포해도 좋을것 같습니다.
