### ISSUE TITLE
Clarification Regarding Albert License Compliance

### ISSUE THREAD

**Issue by ManuelSchneid3r** [hamonikr/hamonikr-albert#7]
Hello,

I recently noticed that HamoniKR distributes a modified version of Albert Launcher. While I am thrilled to see Albert being used in your project, I want to address a concern regarding license compliance.

Albert is licensed under a modified version of the BSD2, which does not allow distributing modified versions. It seems that your version includes changes, such as commenting out the telemetry feature. While I understand the need for platform-specific modifications, I am not comfortable with fundamental changes like disabling telemetry.

Telemetry is vital for me to gauge the user base, and it directly impacts my motivation to continue developing and maintaining Albert. A perceived reduction in users may lead to decreased development efforts. Also by working together to move fixes and improvements upstream, we can ensure all users benefit and maintain consistency across distributions.

I also appreciate the pull requests you have already sent to the project. However, I could not merge them yet because they require some preparatory work, including an overhaul of how translations are structured and packaged, as well as finalizing the ongoing frontend overhaul. Once these dependencies are resolved, I look forward to integrating your contributions into the main project.

To ensure we are aligned, I kindly ask you to not ship modifications and, where possible, to suggest upstream changes. I believe this approach will benefit both projects and the broader Albert user community.

Thank you for your understanding and for your work in promoting Albert. I am happy to discuss this further to find the best path forward.

Best regards,
Manuel/Albert Launcher Developer

**Comment by chaeya** [comment]
Dear @ManuelSchneid3r 

Thank you for your thoughtful message and for raising concerns regarding the distribution of Albert through HamoniKR. We greatly value your contributions to Albert and want to ensure that our actions align with your vision and licensing terms.

After reviewing your feedback and the Albert license, we understand the importance of respecting the license conditions and the role of telemetry in the project's growth and maintenance. As a result, we have taken steps to address your concerns and propose the following:

**Telemetry Feature Re-Enabled**

We have modified our distribution of Albert to re-enable the telemetry feature in alignment with the original design. This decision reflects our commitment to supporting your ability to gauge the user base and maintain motivation for development.
While the feature is enabled by default, we will ensure users are informed about its purpose and functionality to address any privacy concerns.

**Redistribution with Explicit Permission**

We kindly request your explicit written permission to redistribute this revised version of Albert through HamoniKR. This version retains the original telemetry functionality and complies with the Albert license conditions.

**Upstream Collaboration**

We will continue to submit any further changes or improvements to the upstream Albert project. Our goal is to ensure consistency and mutual benefit for both Albert and HamoniKR, while also addressing the needs of our users.
We deeply apologize if any previous actions caused inconvenience or misunderstanding. Your feedback is invaluable, and we are committed to fostering a collaborative relationship that benefits both projects and their users.

Please let us know how we can move forward with this proposal. We are more than happy to adjust our approach based on your guidance and suggestions.

Thank you for your understanding and support.

Best regards,
Kevin Kim
